_extends: release-flow-sample:.github/release-drafter-base.yml
name-template: package-b-v$RESOLVED_VERSION
tag-template: package-b-v$RESOLVED_VERSION
tag-prefix: package-b-
include-paths:
  - "packages/package-b/"
