_extends: release-flow-sample:.github/release-drafter-base.yml
name-template: package-a-v$RESOLVED_VERSION
tag-template: package-a-v$RESOLVED_VERSION
tag-prefix: package-a-
include-paths:
  - "packages/package-a/"
