version-template: '$MAJOR.$MINOR'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: minor
categories:
  - title: '⬆️ Dependencies'
    collapse-after: 3
    labels:
      - 'renovate'
template: |
  ## Changes

  $CHANGES
