
name: Deploy
on:
  release:

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: Log event
        run: "echo Event: ${{ github.event.action }}"
  staging-deploy:
    runs-on: ubuntu-latest
    if: github.event.release.prerelease == true

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Deploy to staging
        run: git status 

  production-deploy:
    runs-on: ubuntu-latest
    if: github.event.release.prerelease == false

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Deploy to production
        run: git status 
