
name: Staging Deploy
on:
  release:
    types: 
      - prereleased

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.release.prerelease == true

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Deploy to staging
        run: git status 
